version: '3'
services:
  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - ./wp-data:/var/lib/mysql
    env_file:
      - db.env
  wordpress:
    image: wordpress:4.8-php7.1-fpm
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./wp-app:/var/www/html
    env_file:
      - wp.env
    depends_on:
      - db
  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wp-app:/var/www/html
    depends_on:
      - wordpress
